name: Label Issues Workflow

on:
  workflow_call:
    inputs:
      labels:
        description: 'Comma-separated list of labels to add to the issue e.g. help wanted,good first issue'
        required: true
        type: string
      issue_number:
        description: 'The number of the issue to label'
        required: true
        type: number
      repo:
        description: 'The repository being labeled'
        required: true
        type: string
    secrets:
      token:
        description: 'GitHub token for authentication'
        required: true

jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add labels to issue
        run: gh issue edit ${{ inputs.issue_number }} --add-label ${{ inputs.labels }} --repo ${{ inputs.repo }}
        env:
          GH_TOKEN: ${{ secrets.token }}
          NUMBER: ${{ inputs.issue_number }}

